### ISSUE TITLE
[Enhancement] Custom Shields for social media accounts and integrations

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/.github#1]
## Description

As a product owner, I want to make while-true-do.io very discoverable, so users and developers can connect easily. I would love to see some custom [shields](https://shields.io) on the profile README that link to our social media accounts and integrations.

## Criteria

- link to twitter
- link to linkedin
- link to docker hub
- link to website
- link to mail
- link to blog
- link to irc
- Link to telegram

## Additional information

- please also take a look at the integration and organization repository to gather ideas of additional meaningful links to the README.

**Comment by daniel-schier** [comment]
This is also a very nice alternative: https://github.com/carlsednaoui/gitsocial
