### ISSUE TITLE
[Enhancement] Link to filtered PR and issues

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/.github#2]
## Description

For discoverability, I want to have some links that point to PR and Issue filters. In best case, one can get an overview of all PRs and Issues where the labels help-wanted or good-first-issue are attached. Additionally, having a shield with all counted PRs and/or open Issues would be awesome.

## Criteria

- evaluate links to show all open issues with help-wanted or good-first issue
- evaluate links to show all open pull requests with help-wanted or good-first issue
- evaluate shields to show all open issues
- evaluate shields to show all open pull requests

## Additional information

- shields.io

**Comment by daniel-schier** [comment]
Example: https://github.com/issues?q=org%3Awhiletruedoio+is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
